"""Mirror plugin/skills/ into .claude/skills/ for local Claude Code project-skill discovery.

plugin/skills/ is the single source of truth shipped in the plugin tree (af-37k.2).
.claude/skills/ is git-ignored and regenerated by this script so local development in
this repo keeps working without duplicating skill files in git.
"""

from __future__ import annotations

import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "plugin" / "skills"
DEST = REPO_ROOT / ".claude" / "skills"


def sync() -> None:
    if DEST.exists():
        shutil.rmtree(DEST)
    shutil.copytree(SOURCE, DEST)
    print(f"synced {sum(1 for _ in DEST.iterdir())} skills into {DEST}")


if __name__ == "__main__":
    sync()
